
admins = set([
    "laffra@gmail.com",
])

EXPIRATION_MINUTE_SECONDS = 60
EXPIRATION_HOUR_SECONDS = 60 * EXPIRATION_MINUTE_SECONDS
EXPIRATION_DAY_SECONDS = 24 * EXPIRATION_HOUR_SECONDS
EXPIRATION_WEEK_SECONDS = 7 * EXPIRATION_DAY_SECONDS